name: cssclasses
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353535'
    - '#d6d6d6'
    - '#b4b4b4'
    - '#858585'
    - '#696969'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
