name: cssclasses
favicon: null
layout_spectrum: 0.2998907892033458
typography_spectrum: 0.7590908603742719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7338007851503789
  lightness: 0.8507153482642025
  saturation: 0.19202662562020123
  rhythmicContrast: 0.9565668061841279
purpose: []
